version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3005:3005
    restart: always
    volumes:
      - ./src:/app/src
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    container_name: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
